default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: kilia_development

test:
  <<: *default
  database: kilia_test

production:
  <<: *default
  database: kilia_production
  